export {default as SwitchLang} from "./SwitchLang.vue";
export {default as AppLogo} from "./AppLogo.vue";
export {default as CustomButton} from "./CustomButton.vue";
export {default as AdminPageHeader} from "./AdminPageHeader.vue";
export {default as CustomCombobox} from "./CustomCombobox.vue";
export {default as LoadingIndicator} from "./LoadingIndicator.vue";
export {default as MenuLink} from "./Link.vue";
export {default as BaseAvatar} from "./BaseAvatar.vue";
export {default as InputPassword} from "./InputPassword.vue";
export {default as Notification} from "./Notification.vue"